Added archive type to metadata
MewsSystems/fiscalization-france pull request #4
Opened 2021-02-11 14:07 UTC by abdallahbeshi

2021-02-11 14:09 UTC, marektresnak approved these changes
I guess we could check that the value is one of the allowed values when parsing metadata. But that would be just adding more logic to the checker and wouldn't bring much value.

2021-02-11 14:17 UTC, marektresnak requested changes

2021-02-11 14:17 UTC, marektresnak commented on src/Program.cs
> +                archive.Metadata.ArchiveType,
Just realized this doesn't work for v1. It needs to be done in a backwards compatible way.

2021-02-11 17:45 UTC, marektresnak commented on src/Model/ArchiveMetadata.cs
> +        public string ArchiveType { get; }
Since we now have the typed model, this should be an option.

2021-02-12 17:05 UTC, marektresnak commented on src/Program.cs
> +                ArchiveVersion.v400, _ => archive.Metadata.ArchiveType.GetOrElse("")
The whole app is written in a way that invalid data lead to a different failure than the actual signature check failure. I would follow this principle here as well and make sure model metadata doesn't even get created if it's missing some information.

2021-02-15 13:02 UTC, KaliCZ approved these changes

2021-02-15 13:02 UTC, merged